In [33]:
import pandas as pd
import numpy as np

In [34]:
df  = pd.read_csv('Churn_Modelling.csv')

In [35]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [36]:
age = df['Age']
age

0       42
1       41
2       42
3       39
4       43
        ..
9995    39
9996    35
9997    36
9998    42
9999    28
Name: Age, Length: 10000, dtype: int64

In [37]:
mean_age = age.mean()
std_age = age.std()

In [38]:
df['Z-score_age'] = (age-mean_age)/std_age

In [39]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Z-score_age
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0.293503
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0.198154
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,0.293503
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0.007456
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0.388852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,0.007456
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,-0.373939
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,-0.278590
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,0.293503
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,-1.041381

In [40]:
df['Z-score_age'].mean()

np.float64(2.390976305832737e-16)

In [41]:
df['Z-score_age'].std()

np.float64(1.0)

In [42]:
for i in df.columns:
    if df[i].dtype == 'object':
        df.drop(columns = i,inplace= True)

In [43]:
df.head()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Z-score_age
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1,0.293503
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0,0.198154
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1,0.293503
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0,0.007456
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0,0.388852

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
std_scaler = StandardScaler()

In [46]:
df_scaled_std = std_scaler.fit_transform(df)

In [47]:
df_scaled_std

array([[-1.73187761, -0.78321342, -0.32622142, ...,  0.02188649,
         1.97716468,  0.29351742],
       [-1.7315312 , -0.60653412, -0.44003595, ...,  0.21653375,
        -0.50577476,  0.19816383],
       [-1.73118479, -0.99588476, -1.53679418, ...,  0.2406869 ,
         1.97716468,  0.29351742],
       ...,
       [ 1.73118479, -1.47928179,  0.60498839, ..., -1.00864308,
         1.97716468, -0.27860412],
       [ 1.7315312 , -0.11935577,  1.25683526, ..., -0.12523071,
         1.97716468,  0.29351742],
       [ 1.73187761, -0.87055909,  1.46377078, ..., -1.07636976,
        -0.50577476, -1.04143285]])

In [48]:
df_scaled_std.mean()

np.float64(5.845990358466224e-16)

In [49]:
df_scaled_std.std()

np.float64(1.0)

In [50]:
Scaled_df = pd.DataFrame(df_scaled_std,columns= df.columns)

In [51]:
Scaled_df

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Z-score_age
0,-1.731878,-0.783213,-0.326221,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886,1.977165,0.293517
1,-1.731531,-0.606534,-0.440036,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534,-0.505775,0.198164
2,-1.731185,-0.995885,-1.536794,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687,1.977165,0.293517
3,-1.730838,0.144767,0.501521,0.007457,-1.387538,-1.225848,0.807737,-1.547768,-1.030670,-0.108918,-0.505775,0.007457
4,-1.730492,0.652659,2.063884,0.388871,-1.041760,0.785728,-0.911583,0.646092,0.970243,-0.365276,-0.505775,0.388871
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.730492,-1.177652,1.246488,0.007457,-0.004426,-1.225848,0.807737,0.646092,-1.030670,-0.066419,-0.505775,0.007457
9996,1.730838,-1.682806,-1.391939,-0.373958,1.724464,-0.306379,-0.911583,0.646092,0.970243,0.027988,-0.505775,-0.373958
9997,1.731185,-1.479282,0.604988,-0.278604,0.687130,-1.225848,-0.911583,-1.547768,0.970243,-1.008643,1.977165,-0.278604
9998,1.731531,-0.119356,1.256835,0.293517,-0.695982,-0.022608,0.807737,0.646092,-1.030670,-0.125231,1.977165,0.293517
9999,1.731878,-0.870559,1.463771,-1.041433,-0.350204,0.859965,-0.911583,0.646092,-1.030670,-1.076370,-0.505775,-1.041433

In [52]:
from sklearn.preprocessing import MinMaxScaler

In [53]:
scaled_norm = MinMaxScaler()
norm_df = scaled_norm.fit_transform(df)

In [54]:
norm_df

array([[0.00000000e+00, 2.75616127e-01, 5.38000000e-01, ...,
        5.06734893e-01, 1.00000000e+00, 3.24324324e-01],
       [1.00010001e-04, 3.26454364e-01, 5.16000000e-01, ...,
        5.62708739e-01, 0.00000000e+00, 3.10810811e-01],
       [2.00020002e-04, 2.14421435e-01, 3.04000000e-01, ...,
        5.69654352e-01, 1.00000000e+00, 3.24324324e-01],
       ...,
       [9.99799980e-01, 7.53273144e-02, 7.18000000e-01, ...,
        2.10390092e-01, 1.00000000e+00, 2.43243243e-01],
       [9.99899990e-01, 4.66636532e-01, 8.44000000e-01, ...,
        4.64429053e-01, 1.00000000e+00, 3.24324324e-01],
       [1.00000000e+00, 2.50483021e-01, 8.84000000e-01, ...,
        1.90914232e-01, 0.00000000e+00, 1.35135135e-01]])

In [55]:
df  = pd.read_csv('Churn_Modelling.csv')

In [56]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [58]:
df.drop(columns = 'Surname',inplace = True)

In [59]:
df.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [60]:
cat = df[['Geography','Gender']]

In [61]:
cat.head()

  Geography  Gender
0    France  Female
1     Spain  Female
2    France  Female
3    France  Female
4     Spain  Female

In [64]:
cat["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [70]:
cat["Gender_num"]=None

C:\Users\HP\AppData\Local\Temp\ipykernel_8940\154847213.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat["Gender_num"]=None

In [71]:
cat

     Geography  Gender Gender_num
0       France  Female       None
1        Spain  Female       None
2       France  Female       None
3       France  Female       None
4        Spain  Female       None
...        ...     ...        ...
9995    France    Male       None
9996    France    Male       None
9997    France  Female       None
9998   Germany    Male       None
9999    France  Female       None

[10000 rows x 3 columns]

In [72]:
cat['Gender'] = cat['Gender'].map({'Female': 0, 'Male': 1})

C:\Users\HP\AppData\Local\Temp\ipykernel_8940\1186409993.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat['Gender'] = cat['Gender'].map({'Female': 0, 'Male': 1})

In [73]:
cat.head()

  Geography  Gender Gender_num
0    France       0       None
1     Spain       0       None
2    France       0       None
3    France       0       None
4     Spain       0       None

In [74]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [75]:
cat["Geography"]=le.fit_transform(cat["Geography"])
cat["Gender"]=le.fit_transform(cat["Gender"])

C:\Users\HP\AppData\Local\Temp\ipykernel_8940\1307340816.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat["Geography"]=le.fit_transform(cat["Geography"])
C:\Users\HP\AppData\Local\Temp\ipykernel_8940\1307340816.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat["Gender"]=le.fit_transform(cat["Gender"])

In [76]:
cat

      Geography  Gender Gender_num
0             0       0       None
1             2       0       None
2             0       0       None
3             0       0       None
4             2       0       None
...         ...     ...        ...
9995          0       1       None
9996          0       1       None
9997          0       0       None
9998          1       1       None
9999          0       0       None

[10000 rows x 3 columns]

In [77]:
cat = df[['Geography','Gender']]

In [78]:
cat.head()

  Geography  Gender
0    France  Female
1     Spain  Female
2    France  Female
3    France  Female
4     Spain  Female

In [79]:
from sklearn.preprocessing import LabelEncoder
le_geo = LabelEncoder()
le_gen = LabelEncoder()

In [80]:
cat['Geography'] = le_geo.fit_transform(cat['Geography'])
cat['Gender'] = le_gen.fit_transform(cat['Gender'])

C:\Users\HP\AppData\Local\Temp\ipykernel_8940\1014869788.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat['Geography'] = le_geo.fit_transform(cat['Geography'])
C:\Users\HP\AppData\Local\Temp\ipykernel_8940\1014869788.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat['Gender'] = le_gen.fit_transform(cat['Gender'])

In [82]:
cat.head()

   Geography  Gender
0          0       0
1          2       0
2          0       0
3          0       0
4          2       0

In [85]:
le_gen.inverse_transform(cat['Gender'])

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [86]:
le_geo.inverse_transform(cat['Geography'])

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [87]:
cat = df[['Geography','Gender']]

In [89]:
cat.head() #one hot encoding

  Geography  Gender
0    France  Female
1     Spain  Female
2    France  Female
3    France  Female
4     Spain  Female

In [90]:
cat = pd.get_dummies(cat,columns = ['Geography','Gender'],dtype=int)

In [91]:
cat

,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,1,0,0,1,0
1,0,0,1,1,0
2,1,0,0,1,0
3,1,0,0,1,0
4,0,0,1,1,0
...,...,...,...,...,...
9995,1,0,0,0,1
9996,1,0,0,0,1
9997,1,0,0,1,0
9998,0,1,0,0,1
9999,1,0,0,1,0