# Pivot

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
            'Date': ['2024-01-01', '2024-01-01', '2024-01-02', '2024-01-02'],
            'City': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
            'Temperature': [30, 25, 32, 28]
        }
df=pd.DataFrame(data)
print(df)
print()

pivot_df=df.pivot(index='Date',columns='City',values='Temperature')
print(pivot_df)

         Date         City  Temperature
0  2024-01-01     New York           30
1  2024-01-01  Los Angeles           25
2  2024-01-02     New York           32
3  2024-01-02  Los Angeles           28

City        Los Angeles  New York
Date
2024-01-01           25        30
2024-01-02           28        32

In [15]:
df1=pd.read_excel(r'C:\Users\HS\Desktop\Data Analytics\3.DataFrame\Concate And Merge\Sample - Superstore.xlsx')

In [17]:
df1

,A`,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,4962,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,98103.0,West,FUR-CH-10004477,Furniture,Chairs,"Global Push Button Manager's Chair, Indigo",48.712,1,0.2,5.4801
1,4963,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,98103.0,West,OFF-AR-10001427,Office Supplies,Art,Newell 330,17.940,3,0.0,4.6644
2,4964,CA-2016-156587,2016-03-07,2016-03-08,First Class,AB-10015,Aaron Bergman,Consumer,United States,Seattle,...,98103.0,West,OFF-ST-10002344,Office Supplies,Storage,"Carina 42""Hx23 3/4""W Media Storage Unit",242.940,3,0.0,4.8588
3,8223,CA-2016-152905,2016-02-18,2016-02-24,Standard Class,AB-10015,Aaron Bergman,Consumer,United States,Arlington,...,76017.0,Central,OFF-ST-10000321,Office Supplies,Storage,Akro Stacking Bins,12.624,2,0.2,-2.5248
4,8802,CA-2018-140935,2018-11-10,2018-11-12,First Class,AB-10015,Aaron Bergman,Consumer,United States,Oklahoma City,...,73120.0,Central,TEC-PH-10000562,Technology,Phones,Samsung Convoy 3,221.980,2,0.0,62.1544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,3815,CA-2018-152471,2018-07-08,2018-07-08,Same Day,ZD-21925,Zuschuss Donatelli,Consumer,United States,Jacksonville,...,32216.0,South,TEC-PH-10002824,Technology,Phones,Jabra SPEAK 410 Multidevice Speakerphone,823.960,5,0.2,51.4975
9990,3816,CA-2018-152471,2018-07-08,2018-07-08,Same Day,ZD-21925,Zuschuss Donatelli,Consumer,United States,Jacksonville,...,32216.0,South,OFF-PA-10004965,Office Supplies,Paper,Xerox 1921,15.984,2,0.2,4.9950
9991,5898,CA-2018-167682,2018-04-03,2018-04-09,Standard Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,Richmond,...,47374.0,Central,FUR-FU-10003799,Furniture,Furnishings,"Seth Thomas 13 1/2"" Wall Clock",71.120,4,0.0,22.0472
9992,5899,CA-2018-167682,2018-04-03,2018-04-09,Standard Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,Richmond,...,47374.0,Central,TEC-PH-10000673,Technology,Phones,Plantronics Voyager Pro HD - Bluetooth Headset,259.960,4,0.0,124.7808
9993,8342,CA-2019-141481,2019-06-11,2019-06-14,First Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,Los Angeles,...,90036.0,West,OFF-AP-10004532,Office Supplies,Appliances,Kensington 6 Outlet Guardian Standard Surge Pr...,61.440,3,0.0,16.5888

In [21]:
df1.shape

(9994, 21)

In [23]:
df1.columns

Index(['A`', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country/Region', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [25]:
df2=df1[['Region','Category','Sub-Category','Sales']]

In [27]:
df2

       Region         Category Sub-Category    Sales
0        West        Furniture       Chairs   48.712
1        West  Office Supplies          Art   17.940
2        West  Office Supplies      Storage  242.940
3     Central  Office Supplies      Storage   12.624
4     Central       Technology       Phones  221.980
...       ...              ...          ...      ...
9989    South       Technology       Phones  823.960
9990    South  Office Supplies        Paper   15.984
9991  Central        Furniture  Furnishings   71.120
9992  Central       Technology       Phones  259.960
9993     West  Office Supplies   Appliances   61.440

[9994 rows x 4 columns]

# Example2

In [30]:
stocks=pd.read_csv('stocks.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'stocks.csv'