In [2]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_xml('MyxmlFile.xml')

In [6]:
df

                          loc               lastmod changefreq
0  https://example.com/item-1  2022-06-02T00:00:00Z     weekly
1  https://example.com/item-2  2022-06-02T11:34:37Z     weekly
2  https://example.com/item-3  2022-06-03T19:24:47Z     weekly

In [7]:
data=pd.read_xml('Dataxml.xml')

In [8]:
data

     name            email grade  age
0    John    john@mail.com     A   16
1   Alice   alice@mail.com     B   17
2     Bob     bob@mail.com     C   16
3  Hannah  hannah@mail.com     A   17

# Processing Xml in python

# Introduction to elementTree

In [9]:
import numpy as np
import pandas as pd
import xml.etree.ElementTree as ET

# Parsing XML data

In [10]:
tree=ET.parse('Movie.xml')

In [11]:
tree

In [12]:
root=tree.getroot()

In [13]:
root

In [14]:
root.tag

'collection'

In [15]:
root.attrib

{}

# For loop

In [16]:
for child in root:
    print(child.tag,child.attrib)

genre {'category': 'Action'}
genre {'category': 'Thriller'}

In [17]:
[elem.tag for elem in root.iter()]

['collection',
 'genre',
 'decade',
 'movie',
 'format',
 'year',
 'rating',
 'description',
 'movie',
 'format',
 'year',
 'rating',
 'description',
 'movie',
 'format',
 'year',
 'rating',
 'description',
 'decade',
 'movie',
 'format',
 'year',
 'rating',
 'description',
 'movie',
 'format',
 'year',
 'rating',
 'description',
 'movie',
 'format',
 'year',
 'rating',
 'description',
 'genre',
 'decade',
 'movie',
 'format',
 'year',
 'rating',
 'description',
 'decade',
 'movie',
 'format',
 'year',
 'rating',
 'description',
 'movie',
 'format',
 'year',
 'rating',
 'description']

In [18]:
root.iter()

In [19]:
for elem in root.iter():
    print(elem)

<Element 'collection' at 0x0000022BDD255260>
<Element 'genre' at 0x0000022BDD2800E0>
<Element 'decade' at 0x0000022BDD2801D0>
<Element 'movie' at 0x0000022BDD280220>
<Element 'format' at 0x0000022BDD280270>
<Element 'year' at 0x0000022BDD2802C0>
<Element 'rating' at 0x0000022BDD280310>
<Element 'description' at 0x0000022BDD280360>
<Element 'movie' at 0x0000022BDD2803B0>
<Element 'format' at 0x0000022BDD280400>
<Element 'year' at 0x0000022BDD280450>
<Element 'rating' at 0x0000022BDD2804A0>
<Element 'description' at 0x0000022BDD2804F0>
<Element 'movie' at 0x0000022BDD280540>
<Element 'format' at 0x0000022BDD280590>
<Element 'year' at 0x0000022BDD2805E0>
<Element 'rating' at 0x0000022BDD280630>
<Element 'description' at 0x0000022BDD280680>
<Element 'decade' at 0x0000022BDD2806D0>
<Element 'movie' at 0x0000022BDD280720>
<Element 'format' at 0x0000022BDD280770>
<Element 'year' at 0x0000022BDD2807C0>
<Element 'rating' at 0x0000022BDD280810>
<Element 'description' at 0x0000022BDD280860>
<Element 'movie' at 0x0000022BDD2808B0>
<Element 'format' at 0x0000022BDD280900>
<Element 'year' at 0x0000022BDD280950>
<Element 'rating' at 0x0000022BDD2809A0>
<Element 'description' at 0x0000022BDD2809F0>
<Element 'movie' at 0x0000022BDD280A40>
<Element 'format' at 0x0000022BDD280A90>
<Element 'year' at 0x0000022BDD280AE0>
<Element 'rating' at 0x0000022BDD280B30>
<Element 'description' at 0x0000022BDD280B80>
<Element 'genre' at 0x0000022BDD280BD0>
<Element 'decade' at 0x0000022BDD280C20>
<Element 'movie' at 0x0000022BDD280C70>
<Element 'format' at 0x0000022BDD280CC0>
<Element 'year' at 0x0000022BDD280D10>
<Element 'rating' at 0x0000022BDD280D60>
<Element 'description' at 0x0000022BDD280DB0>
<Element 'decade' at 0x0000022BDD280E00>
<Element 'movie' at 0x0000022BDD280EA0>
<Element 'format' at 0x0000022BDD280EF0>
<Element 'year' at 0x0000022BD4FF4680>
<Element 'rating' at 0x0000022BD4FF49A0>
<Element 'description' at 0x0000022BD4FF4860>
<Element 'movie' at 0x0000022BD4FF4630>
<Element 'format' at 0x0000022BD4FF4540>
<Element 'year' at 0x0000022BD4FF4770>
<Element 'rating' at 0x0000022BD4FF4810>
<Element 'description' at 0x0000022BD4FF48B0>

In [20]:
[movie.attrib for movie in root.iter('movie')]

[{'favorite': 'True', 'title': 'Indiana Jones: The raiders of the lost Ark'},
 {'favorite': 'True', 'title': 'THE KARATE KID'},
 {'favorite': 'False', 'title': 'Back 2 the Future'},
 {'favorite': 'False', 'title': 'X-Men'},
 {'favorite': 'True', 'title': 'Batman Returns'},
 {'favorite': 'False', 'title': 'Reservoir Dogs'},
 {'favorite': 'False', 'title': 'ALIEN'},
 {'favorite': 'True', 'title': "Ferris Bueller's Day Off"},
 {'favorite': 'FALSE', 'title': 'American Psycho'}]

In [21]:
for movie in root.iter('movie'):
    print(movie)

<Element 'movie' at 0x0000022BDD280220>
<Element 'movie' at 0x0000022BDD2803B0>
<Element 'movie' at 0x0000022BDD280540>
<Element 'movie' at 0x0000022BDD280720>
<Element 'movie' at 0x0000022BDD2808B0>
<Element 'movie' at 0x0000022BDD280A40>
<Element 'movie' at 0x0000022BDD280C70>
<Element 'movie' at 0x0000022BDD280EA0>
<Element 'movie' at 0x0000022BD4FF4630>

In [22]:
for decade in root.iter('decade'):
    print(decade)

<Element 'decade' at 0x0000022BDD2801D0>
<Element 'decade' at 0x0000022BDD2806D0>
<Element 'decade' at 0x0000022BDD280C20>
<Element 'decade' at 0x0000022BDD280E00>

In [23]:
for format in root.iter('format'):
    print(format)

<Element 'format' at 0x0000022BDD280270>
<Element 'format' at 0x0000022BDD280400>
<Element 'format' at 0x0000022BDD280590>
<Element 'format' at 0x0000022BDD280770>
<Element 'format' at 0x0000022BDD280900>
<Element 'format' at 0x0000022BDD280A90>
<Element 'format' at 0x0000022BDD280CC0>
<Element 'format' at 0x0000022BDD280EF0>
<Element 'format' at 0x0000022BD4FF4540>

# Description

In [24]:
[description.attrib for description in root.iter('description')]

[{}, {}, {}, {}, {}, {}, {}, {}, {}]

In [25]:
[description.text for description in root.iter('description')]

["\n                'Archaeologist and adventurer Indiana Jones \n                is hired by the U.S. government to find the Ark of  the Covenant before the Nazis.'\n                ",
 'None provided.',
 'Marty McFly',
 'Two mutants come to a private academy for their kind whose resident superhero team must oppose a terrorist organization with similar powers.',
 'NA.',
 'WhAtEvER I Want!!!?!',
 '"""""""""',
 'Funny movie on funny guy ',
 'psychopathic Bateman']