In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv("employee_data_200.csv")

In [4]:
df.shape

(250, 10)

In [5]:
df.ndim

2

In [6]:
df.columns

Index(['EmpId', 'FirstNme', 'LstName', 'Dept', 'Positon', 'Slary', 'HireDat',
       'BrthDate', 'Phne', 'Emil'],
      dtype='object')

In [7]:
#Load the CSV file employee_data_200.csv into a DataFrame
df.head(10)

,EmpId,FirstNme,LstName,Dept,Positon,Slary,HireDat,BrthDate,Phne,Emil
0,45,John,Smith,IT,Consultant,72572,2016-10-11,1990-03-24,555-4321,bob.johnson@example.com
1,48,John,Smith,Sales,Consultant,57951,2018-03-27,1977-01-26,555-8765,john.doe@example.com
2,65,Jane,Smith,Finance,Manager,93005,2016-11-24,1989-12-05,555-8765,john.doe@example.com
3,68,Bob,Doe,HR,Developer,68007,2016-07-08,1974-02-01,555-3456,jane.smith@example.com
4,68,John,Williams,IT,Developer,56091,2020-09-14,1980-04-25,555-5678,jane.smith@example.com
5,10,Alice,Doe,HR,Developer,84381,2015-12-22,1973-02-28,555-1234,jane.smith@example.com
6,84,Jane,Brown,Finance,Coordinator,91470,2019-09-17,1991-06-13,555-8765,jane.smith@example.com
7,22,Jane,Smith,HR,Consultant,57581,2019-09-27,1996-12-23,555-8765,david.brown@example.com
8,37,David,Brown,HR,Consultant,72111,2015-03-23,1974-07-23,555-5678,john.doe@example.com
9,88,John,Doe,Marketing,Analyst,78782,2020-09-17,1979-05-17,555-4321,jane.smith@example.com

In [8]:
df.tail(10)

,EmpId,FirstNme,LstName,Dept,Positon,Slary,HireDat,BrthDate,Phne,Emil
240,33,Jane,Williams,IT,Developer,60525,2016-01-13,1993-10-03,555-5678,alice.williams@example.com
241,22,Jane,Brown,Finance,Coordinator,91847,2016-05-13,1996-08-30,555-5678,bob.johnson@example.com
242,100,Alice,Smith,IT,Manager,75983,2015-01-17,1992-12-16,555-1234,bob.johnson@example.com
243,38,David,Williams,Marketing,Coordinator,89855,2020-07-16,1983-08-24,555-5678,bob.johnson@example.com
244,4,John,Johnson,Finance,Developer,80642,2015-07-01,1992-01-01,555-4321,alice.williams@example.com
245,95,Bob,Brown,Marketing,Analyst,55912,2020-03-08,1973-03-21,555-5678,jane.smith@example.com
246,37,John,Doe,Sales,Coordinator,94503,2018-01-28,1976-05-02,555-1234,jane.smith@example.com
247,48,Alice,Smith,IT,Developer,74354,2015-04-27,1984-10-07,555-5678,alice.williams@example.com
248,99,Jane,Brown,IT,Developer,70594,2018-05-19,1998-03-16,555-5678,john.doe@example.com
249,30,David,Johnson,Finance,Coordinator,66138,2017-10-25,1978-10-17,555-3456,alice.williams@example.com

In [9]:
df.columns.values.tolist()

['EmpId',
 'FirstNme',
 'LstName',
 'Dept',
 'Positon',
 'Slary',
 'HireDat',
 'BrthDate',
 'Phne',
 'Emil']

In [10]:
df.Dept.unique()

array(['IT', 'Sales', 'Finance', 'HR', 'Marketing'], dtype=object)

In [12]:
df.Positon.unique()

array(['Consultant', 'Manager', 'Developer', 'Coordinator', 'Analyst'],
      dtype=object)

In [ ]:
df.Dept.