In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel("Case Study 1 - DataFrame.xlsx")

In [3]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,1,Agar,1457129.800,0,7709,93544,0,944357.90,1297245.000,0,...,6899,83687,0,857194.60,1049675.000,0,5749,68253,0,703404.60
1,2,Alirajpur,2241438.350,0,6567,0,104937,1053092.40,2144217.349,0,...,5828,0,90108,907747.20,1481401.499,0,5377,0,80744,809712.40
2,3,Anuppur,1281467.860,0,12145,0,126349,2371616.10,798548.200,0,...,9919,0,104520,2051071.00,669387.400,0,9805,0,101887,2003173.00
3,4,Ashoknagar,1805348.600,0,17894,0,119056,1713077.10,1298031.200,0,...,11825,0,81954,1264502.70,888981.000,0,8579,0,59555,994021.00
4,5,Balaghat,3086169.460,0,63455,240633,71601,6267965.35,2500368.840,0,...,57342,182526,69310,5863967.25,1830778.960,0,54486,175027,65761,5586263.29
5,6,Barwani,4847179.940,0,32995,0,210448,2405514.07,4443589.180,0,...,30456,0,192999,2271105.40,4260575.900,0,30089,0,190928,2228813.40
6,7,Betul,3559867.230,0,29610,92642,190914,5087669.76,2542444.300,0,...,26683,88771,169707,4604278.20,2047258.800,0,24293,82281,154538,4278763.20
7,8,Bhind,2714206.450,0,11564,189020,0,2344839.52,1271146.200,0,...,4947,89663,0,1135546.00,862517.200,0,3741,68796,0,881423.40
8,9,Bhopal,6083432.100,0,21600,315332,0,4233877.80,5857256.400,0,...,15204,200514,0,3592618.40,4003512.800,0,14723,189068,0,3569652.40
9,10,Burhanpur,1978253.390,0,7587,67948,31373,1705304.65,1574439.000,0,...,6310,46166,20684,1431032.00,1454698.000,0,5921,45186,18040,1369633.00
10,11,Chhatarpur,4093812.050,0,30592,0,263035,3844718.81,3501408.340,0,...,28483,0,240897,3613113.41,2927342.340,0,24714,0,209951,3190616.81
11,12,Chhindwara,2643480.260,0,31693,194638,94987,4751396.85,1522180.310,0,...,16936,123831,49559,3141933.00,1070627.310,0,13386,107730,34841,2587147.00
12,13,Damoh,2846658.940,0,19154,0,193123,2826584.44,2813760.560,0,...,18748,0,188192,2794282.24,2226152.400,0,16441,0,167234,2460583.08
13,14,Datia,1468599.000,0,5369,114124,0,1605663.00,1160326.400,0,...,4533,90963,0,1368162.40,1029332.200,0,4017,82117,0,1262785.40
14,15,Dewas,3454410.000,0,20626,206710,0,3007478.05,2448676.000,0,...,15494,146951,0,2414794.40,1853104.000,0,13122,121134,0,2058355.00
15,16,Dhar,5093033.800,0,32330,42089,265883,4155794.24,3662687.400,0,...,26168,30942,193562,3534780.80,3350342.200,0,24899,28962,185619,3415485.00
16,17,Dindori,2022044.980,0,20702,0,136903,2830587.60,1154915.400,0,...,19030,0,125753,2716112.00,868777.200,0,17280,0,115364,2495620.00
17,18,Guna,3060446.250,0,30791,0,198671,3010902.54,2543718.050,0,...,23954,0,134156,2655354.54,2108269.600,0,21751,0,119422,2503806.20
18,19,Gwalior,3594512.800,0,19429,241449,0,3194437.30,3204463.200,0,...,16579,204265,0,2908404.40,2838411.400,0,14714,191236,0,2765668.40
19,20,Harda,1105942.200,0,5249,67373,0,936356.80,784929.000,0,...,4263,53603,0,818112.00,673048.000,0,3788,48383,0,748422.00
20,21,Indore,5751567.110,0,17919,279387,0,5233920.26,4923363.160,0,...,13201,157229,0,4115828.06,4141787.100,0,12801,149893,0,4068316.76
21,22,Jabalpur,4118444.700,0,40581,331448,0,3924573.46,3290480.570,0,...,23983,206465,0,2527445.20,1648331.900,0,18037,157411,0,1931778.40
22,23,Jhabua,3127590.630,0,17736,0,174586,2718451.90,2515905.000,0,...,14975,0,152885,2419644.00,2067326.000,0,13706,0,143840,2272690.00
23,24,Katni,2502210.680,0,6620,187692,0,2385482.00,2089186.280,0,...,6023,126363,0,2185026.40,1489295.000,0,4815,88030,0,1792233.00
24,25,Khandwa,3342074.400,0,26345,0,228401,2837514.10,2598727.200,0,...,22152,0,191645,2390469.00,2322958.800,0,21680,0,187032,2326847.00
25,26,Khargone,4964625.560,0,31105,70299,184843,3226256.71,4374465.660,0,...,25604,55521,151173,2620013.60,3771889.200,0,23936,51947,140435,2477612.10
26,27,Maihar,1655094.900,0,17027,78014,0,1674650.40,1401369.200,0,...,9435,34049,0,1262300.00,678998.400,0,6975,23821,0,833827.60
27,28,Mandla,2280551.840,0,47517,0,222802,4289256.22,2168908.720,0,...,46607,0,219864,4226038.10,1722030.960,0,44725,0,212672,4098275.60
28,29,Mandsaur,2158715.950,0,8683,171619,0,1401433.95,1981192.000,0,...,6988,120856,0,1188735.00,1766827.000,0,6715,114961,0,1147176.00
29,30,Mauganj,1616902.400,0,16266,106436,0,1537973.40,1346280.200,0,...,7041,85642,0,1274388.30,945556.400,0,6559,68146,0,1069425.20
30,31,Morena,4020494.840,0,14753,270345,0,3252808.06,2854969.200,0,...,6772,170348,0,2355361.80,2127958.200,0,5377,143988,0,1971160.20
31,32,Narmadapuram,2583095.430,0,14686,160774,15328,2441825.50,2174602.350,0,...,13985,150758,15328,2397644.00,2046656.000,0,13638,144396,15327,2376409.00
32,33,NARSINGHPUR,2514647.400,0,22035,199436,0,2563310.00,2001518.600,0,...,15800,179438,0,2337509.40,1422746.600,0,12551,136094,0,1819848.40
33,34,Neemuch,2081465.800,0,8621,119894,0,1353096.20,1859601.000,0,...,6855,85835,0,1118362.60,1689175.000,0,6209,77967,0,1043734.60
34,35,Niwari,1140035.760,0,8438,0,75103,755688.72,848574.040,0,...,5057,0,42239,498194.36,712114.040,0,4242,0,36753,400550.36
35,36,Pandhurna,663132.580,0,7207,64872,0,1096213.12,519629.680,0,...,6282,55721,0,876474.12,344840.480,0,5805,49956,0,734950.12
36,37,Panna,2871726.590,0,22097,0,166948,1894514.72,2869681.990,0,...,22037,0,165884,1889990.20,2659329.780,0,20877,0,156399,1794401.00
37,38,Raisen,3892826.670,0,24880,0,239865,2541607.20,2941827.600,0,...,19610,0,189087,1998091.40,2308755.600,0,17370,0,168902,1856873.40
38,39,Rajgarh,5024521.251,0,26519,0,281442,2465011.39,4337963.160,0,...,22037,0,240328,2142324.64,3524114.320,0,19469,0,213530,1941169.88
39,40,Ratlam,3294682.930,0,14871,135918,42792,2103075.30,2322917.600,0,...,11006,102320,29043,1526087.70,2003343.200,0,10058,94003,26520,1401740.30
40,41,Rewa,3541618.360,0,34060,185169,0,3127365.25,2360618.800,0,...,13511,94681,0,1740247.06,1064351.040,0,9889,55200,0,1148875.00
41,42,Sagar,5777765.200,0,39650,0,399706,4985097.48,3598642.800,0,...,18399,0,238416,3671918.20,2880541.200,0,15459,0,192792,2994618.40
42,43,Satna,3284120.940,0,25585,0,157134,3494029.60,2620891.400,0,...,10020,0,95410,2767039.20,1916405.600,0,8679,0,81091,2193774.20
43,44,Sehore,3535351.800,0,16940,220002,0,3031501.60,2964433.000,0,...,15517,202655,0,2842194.00,2477486.000,0,13831,184623,0,2608880.00
44,45,Seoni,1664219.600,0,33038,104279,127859,4721936.60,1211978.600,0,...,24729,57823,89694,3628956.40,862553.000,0,19460,53345,73034,2835711.00
45,46,Shahdol,1980091.430,0,37918,0,203798,3772207.94,1580415.570,0,...,32277,0,162225,3413893.94,1277728.370,0,30356,0,146507,3143751.70
46,47,Shajapur,2307289.900,0,10411,134943,0,2049183.00,1559147.160,0,...,7694,104435,0,1547392.60,1304884.160,0,7327,99217,0,1462449.60
47,48,Sheopur,1524671.750,0,17670,0,78815,967193.50,1198606.000,0,...,10172,0,45971,642351.00,723124.000,0,6193,0,30282,410346.00
48,49,Shivpuri,3508582.350,0,48280,245938,0,3438187.25,2141262.440,0,...,20783,137883,0,2210563.40,1417533.200,0,13678,99342,0,1549087.80
49,50,Sidhi,3170001.750,0,28992,0,173566,2862487.70,2605957.150,0,...,20022,0,113567,2196320.10,1787573.200,0,13802,0,82678,1783676.30
50,51,Singrauli,3229657.400,0,20351,0,139652,2999621.50,2552400.800,0,...,9084,0,74730,2316683.00,1514706.800,0,7918,0,60188,1790535.00
51,52,Tikamgarh,2835139.810,0,21637,0,174747,1854636.65,2347958.560,0,...,15635,0,120284,1379781.55,1885710.880,0,12074,0,96405,1101981.55
52,53,Ujjain,3940400.680,0,19307,213037,0,3085535.05,2470046.020,0,...,8873,127731,0,2211749.20,1786258.550,0,8029,112701,0,2026143.80
53,54,Umaria,1169704.560,0,14947,0,82914,2031102.72,972088.210,0,...,13359,0,74066,1901068.62,788808.600,0,11891,0,66623,1746093.62
54,55,Vidisha,4243674.100,0,19027,0,245274,3096850.50,2983966.000,0,...,17750,0,222621,2697648.60,2649441.800,0,17531,0,218998,2651334.60

In [4]:
#change the name of all columns
Col = ['Sno','District','A-Wheat','A-Rice','A-Sugar','A-Salt','A-FSalt','A-FRice',
       'RO-Wheat','RO-Rice','RO-Sugar','RO-Salt','RO-FSalt','RO-FRice',
       'D-Wheat','D-Rice','D-Sugar','D-Salt','D-FSalt','D-FRice',
       'R-Wheat','R-Rice','R-Sugar','R-Salt','R-FSalt','R-FRice']

In [5]:
df.columns = Col

In [6]:
df.head()

,Sno,District,A-Wheat,A-Rice,A-Sugar,A-Salt,A-FSalt,A-FRice,RO-Wheat,RO-Rice,...,D-Sugar,D-Salt,D-FSalt,D-FRice,R-Wheat,R-Rice,R-Sugar,R-Salt,R-FSalt,R-FRice
0,1,Agar,1457129.80,0,7709,93544,0,944357.90,1297245.000,0,...,6899,83687,0,857194.60,1049675.000,0,5749,68253,0,703404.60
1,2,Alirajpur,2241438.35,0,6567,0,104937,1053092.40,2144217.349,0,...,5828,0,90108,907747.20,1481401.499,0,5377,0,80744,809712.40
2,3,Anuppur,1281467.86,0,12145,0,126349,2371616.10,798548.200,0,...,9919,0,104520,2051071.00,669387.400,0,9805,0,101887,2003173.00
3,4,Ashoknagar,1805348.60,0,17894,0,119056,1713077.10,1298031.200,0,...,11825,0,81954,1264502.70,888981.000,0,8579,0,59555,994021.00
4,5,Balaghat,3086169.46,0,63455,240633,71601,6267965.35,2500368.840,0,...,57342,182526,69310,5863967.25,1830778.960,0,54486,175027,65761,5586263.29

In [7]:
#set Sno columns as index columns
df.set_index('Sno', inplace=True)

In [8]:
df.head()

,District,A-Wheat,A-Rice,A-Sugar,A-Salt,A-FSalt,A-FRice,RO-Wheat,RO-Rice,RO-Sugar,...,D-Sugar,D-Salt,D-FSalt,D-FRice,R-Wheat,R-Rice,R-Sugar,R-Salt,R-FSalt,R-FRice
Sno,,,,,,,,,,,,,,,,,,,,,
1,Agar,1457129.80,0,7709,93544,0,944357.90,1297245.000,0,6946,...,6899,83687,0,857194.60,1049675.000,0,5749,68253,0,703404.60
2,Alirajpur,2241438.35,0,6567,0,104937,1053092.40,2144217.349,0,6542,...,5828,0,90108,907747.20,1481401.499,0,5377,0,80744,809712.40
3,Anuppur,1281467.86,0,12145,0,126349,2371616.10,798548.200,0,10914,...,9919,0,104520,2051071.00,669387.400,0,9805,0,101887,2003173.00
4,Ashoknagar,1805348.60,0,17894,0,119056,1713077.10,1298031.200,0,13068,...,11825,0,81954,1264502.70,888981.000,0,8579,0,59555,994021.00
5,Balaghat,3086169.46,0,63455,240633,71601,6267965.35,2500368.840,0,61466,...,57342,182526,69310,5863967.25,1830778.960,0,54486,175027,65761,5586263.29

In [9]:
df.columns

Index(['District', 'A-Wheat', 'A-Rice', 'A-Sugar', 'A-Salt', 'A-FSalt',
       'A-FRice', 'RO-Wheat', 'RO-Rice', 'RO-Sugar', 'RO-Salt', 'RO-FSalt',
       'RO-FRice', 'D-Wheat', 'D-Rice', 'D-Sugar', 'D-Salt', 'D-FSalt',
       'D-FRice', 'R-Wheat', 'R-Rice', 'R-Sugar', 'R-Salt', 'R-FSalt',
       'R-FRice'],
      dtype='object')

In [10]:
#3 drop all columns which start from RO
df.drop(['RO-Wheat', 'RO-Rice', 'RO-Sugar', 'RO-Salt', 'RO-FSalt',
       'RO-FRice'],axis=1,inplace=True)

In [11]:
df.columns

Index(['District', 'A-Wheat', 'A-Rice', 'A-Sugar', 'A-Salt', 'A-FSalt',
       'A-FRice', 'D-Wheat', 'D-Rice', 'D-Sugar', 'D-Salt', 'D-FSalt',
       'D-FRice', 'R-Wheat', 'R-Rice', 'R-Sugar', 'R-Salt', 'R-FSalt',
       'R-FRice'],
      dtype='object')

In [12]:
#4 add values of same commodity
df['A-RICE'] = df['A-Rice']+df['A-FRice']
df['D-RICE'] = df['D-Rice']+df['D-FRice']
df['R-RICE'] = df['R-Rice']+df['R-FRice']

df['A-SALT'] = df['A-Salt']+df['A-FSalt']
df['D-SALT'] = df['D-Salt']+df['D-FSalt']
df['R-SALT'] = df['R-Salt']+df['R-FSalt']

In [13]:
df.columns

Index(['District', 'A-Wheat', 'A-Rice', 'A-Sugar', 'A-Salt', 'A-FSalt',
       'A-FRice', 'D-Wheat', 'D-Rice', 'D-Sugar', 'D-Salt', 'D-FSalt',
       'D-FRice', 'R-Wheat', 'R-Rice', 'R-Sugar', 'R-Salt', 'R-FSalt',
       'R-FRice', 'A-RICE', 'D-RICE', 'R-RICE', 'A-SALT', 'D-SALT', 'R-SALT'],
      dtype='object')

In [14]:
#5 drop columns which values added in new columns
df.drop(['A-Rice','A-Salt','A-FSalt','A-FRice','D-Rice', 'D-Salt', 'D-FSalt',
       'D-FRice', 'R-Rice', 'R-Salt', 'R-FSalt','R-FRice'],axis=1,inplace=True)

In [15]:
df.columns

Index(['District', 'A-Wheat', 'A-Sugar', 'D-Wheat', 'D-Sugar', 'R-Wheat',
       'R-Sugar', 'A-RICE', 'D-RICE', 'R-RICE', 'A-SALT', 'D-SALT', 'R-SALT'],
      dtype='object')

In [16]:
#6 arrange all the columns in sequence
df = df[['District', 'A-Wheat', 'A-RICE', 'A-SALT', 'A-Sugar', 'D-Wheat','D-RICE', 'D-Sugar', 'D-SALT', 'R-Wheat',
       'R-Sugar',  'R-RICE', 'R-SALT']]

In [17]:
df.columns

Index(['District', 'A-Wheat', 'A-RICE', 'A-SALT', 'A-Sugar', 'D-Wheat',
       'D-RICE', 'D-Sugar', 'D-SALT', 'R-Wheat', 'R-Sugar', 'R-RICE',
       'R-SALT'],
      dtype='object')

In [18]:
L1 = list(df.columns)

In [19]:
L1

['District',
 'A-Wheat',
 'A-RICE',
 'A-SALT',
 'A-Sugar',
 'D-Wheat',
 'D-RICE',
 'D-Sugar',
 'D-SALT',
 'R-Wheat',
 'R-Sugar',
 'R-RICE',
 'R-SALT']

In [20]:
### Q7 Insert D-%W, D-%R,D-%S,D-%FS column at index 9,10,11,12
for i,j in enumerate(L1):
    print(i, " ",j)

0   District
1   A-Wheat
2   A-RICE
3   A-SALT
4   A-Sugar
5   D-Wheat
6   D-RICE
7   D-Sugar
8   D-SALT
9   R-Wheat
10   R-Sugar
11   R-RICE
12   R-SALT

In [21]:
df.insert(loc = 9, column='D-%W', value=round(df['D-Wheat']/df['A-Wheat']*100,0))

In [22]:
df.head(2)

,District,A-Wheat,A-RICE,A-SALT,A-Sugar,D-Wheat,D-RICE,D-Sugar,D-SALT,D-%W,R-Wheat,R-Sugar,R-RICE,R-SALT
Sno,,,,,,,,,,,,,,
1,Agar,1457129.80,944357.9,93544,7709,1269266.000,857194.6,6899,83687,87.0,1049675.000,5749,703404.6,68253
2,Alirajpur,2241438.35,1053092.4,104937,6567,1709208.699,907747.2,5828,90108,76.0,1481401.499,5377,809712.4,80744

In [23]:
for i,j in enumerate(list(df.columns)):
    print(i, " ",j)

0   District
1   A-Wheat
2   A-RICE
3   A-SALT
4   A-Sugar
5   D-Wheat
6   D-RICE
7   D-Sugar
8   D-SALT
9   D-%W
10   R-Wheat
11   R-Sugar
12   R-RICE
13   R-SALT

In [24]:
df.insert(loc = 10, column='D-%R', value=round(df['D-RICE']/df['A-RICE']*100,0))
df.insert(loc = 11, column='D-%S', value=round(df['D-Sugar']/df['A-Sugar']*100,0))
df.insert(loc = 12, column='D-%FS', value=round(df['D-SALT']/df['A-SALT']*100,0))

In [25]:
df.head()

,District,A-Wheat,A-RICE,A-SALT,A-Sugar,D-Wheat,D-RICE,D-Sugar,D-SALT,D-%W,D-%R,D-%S,D-%FS,R-Wheat,R-Sugar,R-RICE,R-SALT
Sno,,,,,,,,,,,,,,,,,
1,Agar,1457129.80,944357.90,93544,7709,1269266.000,857194.60,6899,83687,87.0,91.0,89.0,89.0,1049675.000,5749,703404.60,68253
2,Alirajpur,2241438.35,1053092.40,104937,6567,1709208.699,907747.20,5828,90108,76.0,86.0,89.0,86.0,1481401.499,5377,809712.40,80744
3,Anuppur,1281467.86,2371616.10,126349,12145,699272.200,2051071.00,9919,104520,55.0,86.0,82.0,83.0,669387.400,9805,2003173.00,101887
4,Ashoknagar,1805348.60,1713077.10,119056,17894,1196581.800,1264502.70,11825,81954,66.0,74.0,66.0,69.0,888981.000,8579,994021.00,59555
5,Balaghat,3086169.46,6267965.35,312234,63455,2134451.320,5863967.25,57342,251836,69.0,94.0,90.0,81.0,1830778.960,54486,5586263.29,240788

In [26]:
for i,j in enumerate(list(df.columns)):
    print(i, " ",j)

0   District
1   A-Wheat
2   A-RICE
3   A-SALT
4   A-Sugar
5   D-Wheat
6   D-RICE
7   D-Sugar
8   D-SALT
9   D-%W
10   D-%R
11   D-%S
12   D-%FS
13   R-Wheat
14   R-Sugar
15   R-RICE
16   R-SALT

In [28]:
#Q8 Insert R-%W, R-%R,R-%S,R-%FS column at index 17,18,19,20¶
df.insert(loc = 17, column='R-%W', value=round(df['R-Wheat']/df['A-Wheat']*100,0))
df.insert(loc = 18, column='R-%R', value=round(df['R-RICE']/df['A-RICE']*100,0))
df.insert(loc = 19, column='R-%S', value=round(df['R-Sugar']/df['A-Sugar']*100,0))
df.insert(loc = 20, column='R-%FS', value=round(df['R-SALT']/df['A-SALT']*100,0))

In [29]:
df.columns

Index(['District', 'A-Wheat', 'A-RICE', 'A-SALT', 'A-Sugar', 'D-Wheat',
       'D-RICE', 'D-Sugar', 'D-SALT', 'D-%W', 'D-%R', 'D-%S', 'D-%FS',
       'R-Wheat', 'R-Sugar', 'R-RICE', 'R-SALT', 'R-%W', 'R-%R', 'R-%S',
       'R-%FS'],
      dtype='object')

In [30]:
df1 = df[['District', 'A-Wheat', 'A-RICE', 'A-SALT', 'A-Sugar',  
          'D-%W', 'D-%R', 'D-%S', 'D-%FS',
           'R-%W', 'R-%R', 'R-%S','R-%FS']]

In [31]:
for i,j in enumerate (list(df1.columns)):
    print(i," ",j)

0   District
1   A-Wheat
2   A-RICE
3   A-SALT
4   A-Sugar
5   D-%W
6   D-%R
7   D-%S
8   D-%FS
9   R-%W
10   R-%R
11   R-%S
12   R-%FS

In [32]:
### Q9 Insert Avg-D-%WR and Avg-R-%WR columns at index 7 and 12
df1.insert(loc=7, column="Avg-D-%WR", value=round(((df1['D-%W']+df1['D-%R'])/2),0))
df1.insert(loc=12, column="Avg-R-%WR", value=round(((df1['R-%W']+df1['R-%R'])/2),0))

In [33]:
df1.sort_values('Avg-R-%WR', ignore_index=True).head(2)

,District,A-Wheat,A-RICE,A-SALT,A-Sugar,D-%W,D-%R,Avg-D-%WR,D-%S,D-%FS,R-%W,R-%R,Avg-R-%WR,R-%S,R-%FS
0,Rewa,3541618.36,3127365.25,185169,34060,49.0,56.0,52.0,40.0,51.0,30.0,37.0,34.0,29.0,30.0
1,Bhind,2714206.45,2344839.52,189020,11564,44.0,48.0,46.0,43.0,47.0,32.0,38.0,35.0,32.0,36.0

In [34]:
df1['A-Wheat'] = round((df1['A-Wheat'])/1000,0)
df1['A-RICE'] = round((df1['A-RICE'])/1000,0)
df1['A-SALT'] = round((df1['A-SALT'])/1000,0)
df1['A-Sugar'] = round((df1['A-Sugar'])/1000,0)

C:\Users\HP\AppData\Local\Temp\ipykernel_8520\3014088575.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['A-Wheat'] = round((df1['A-Wheat'])/1000,0)
C:\Users\HP\AppData\Local\Temp\ipykernel_8520\3014088575.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['A-RICE'] = round((df1['A-RICE'])/1000,0)
C:\Users\HP\AppData\Local\Temp\ipykernel_8520\3014088575.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['A-SALT'] = round((df1['A-SALT'])/1000,0)
C:\Users\HP\AppData\Local\Temp\ipykernel_8520\3014088575.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['A-Sugar'] = round((df1['A-Sugar'])/1000,0)

In [35]:
#10 sort table on the basis of avg-R-%WR columns
df1.head()

,District,A-Wheat,A-RICE,A-SALT,A-Sugar,D-%W,D-%R,Avg-D-%WR,D-%S,D-%FS,R-%W,R-%R,Avg-R-%WR,R-%S,R-%FS
Sno,,,,,,,,,,,,,,,
1,Agar,1457.0,944.0,94.0,8.0,87.0,91.0,89.0,89.0,89.0,72.0,74.0,73.0,75.0,73.0
2,Alirajpur,2241.0,1053.0,105.0,7.0,76.0,86.0,81.0,89.0,86.0,66.0,77.0,72.0,82.0,77.0
3,Anuppur,1281.0,2372.0,126.0,12.0,55.0,86.0,70.0,82.0,83.0,52.0,84.0,68.0,81.0,81.0
4,Ashoknagar,1805.0,1713.0,119.0,18.0,66.0,74.0,70.0,66.0,69.0,49.0,58.0,54.0,48.0,50.0
5,Balaghat,3086.0,6268.0,312.0,63.0,69.0,94.0,82.0,90.0,81.0,59.0,89.0,74.0,86.0,77.0

In [36]:
df1.columns

Index(['District', 'A-Wheat', 'A-RICE', 'A-SALT', 'A-Sugar', 'D-%W', 'D-%R',
       'Avg-D-%WR', 'D-%S', 'D-%FS', 'R-%W', 'R-%R', 'Avg-R-%WR', 'R-%S',
       'R-%FS'],
      dtype='object')

In [37]:
df1[['District','Avg-R-%WR']].sort_values('Avg-R-%WR',ignore_index=True).head(3)

   District  Avg-R-%WR
0      Rewa       34.0
1     Bhind       35.0
2  Shivpuri       42.0

In [38]:
df1[['District','Avg-R-%WR']].sort_values('Avg-R-%WR',ascending=False,ignore_index=True).head(3)

       District  Avg-R-%WR
0         Panna       94.0
1       Barwani       90.0
2  Narmadapuram       88.0

In [39]:
df1[['District','Avg-D-%WR']].sort_values('Avg-D-%WR',ignore_index=True).head(3)

     District  Avg-D-%WR
0       Bhind       46.0
1        Rewa       52.0
2  Chhindwara       58.0

In [40]:
df1[['District','Avg-D-%WR']].sort_values('Avg-D-%WR',ascending=False,ignore_index=True).head(3)

  District  Avg-D-%WR
0    Panna      100.0
1    Damoh       99.0
2   Mandla       95.0

In [41]:
#11 Export table in excel
df1

,District,A-Wheat,A-RICE,A-SALT,A-Sugar,D-%W,D-%R,Avg-D-%WR,D-%S,D-%FS,R-%W,R-%R,Avg-R-%WR,R-%S,R-%FS
Sno,,,,,,,,,,,,,,,
1,Agar,1457.0,944.0,94.0,8.0,87.0,91.0,89.0,89.0,89.0,72.0,74.0,73.0,75.0,73.0
2,Alirajpur,2241.0,1053.0,105.0,7.0,76.0,86.0,81.0,89.0,86.0,66.0,77.0,72.0,82.0,77.0
3,Anuppur,1281.0,2372.0,126.0,12.0,55.0,86.0,70.0,82.0,83.0,52.0,84.0,68.0,81.0,81.0
4,Ashoknagar,1805.0,1713.0,119.0,18.0,66.0,74.0,70.0,66.0,69.0,49.0,58.0,54.0,48.0,50.0
5,Balaghat,3086.0,6268.0,312.0,63.0,69.0,94.0,82.0,90.0,81.0,59.0,89.0,74.0,86.0,77.0
6,Barwani,4847.0,2406.0,210.0,33.0,90.0,94.0,92.0,92.0,92.0,88.0,93.0,90.0,91.0,91.0
7,Betul,3560.0,5088.0,284.0,30.0,68.0,90.0,79.0,90.0,91.0,58.0,84.0,71.0,82.0,84.0
8,Bhind,2714.0,2345.0,189.0,12.0,44.0,48.0,46.0,43.0,47.0,32.0,38.0,35.0,32.0,36.0
9,Bhopal,6083.0,4234.0,315.0,22.0,70.0,85.0,78.0,70.0,64.0,66.0,84.0,75.0,68.0,60.0
10,Burhanpur,1978.0,1705.0,99.0,8.0,79.0,84.0,82.0,83.0,67.0,74.0,80.0,77.0,78.0,64.0
11,Chhatarpur,4094.0,3845.0,263.0,31.0,84.0,94.0,89.0,93.0,92.0,72.0,83.0,78.0,81.0,80.0
12,Chhindwara,2643.0,4751.0,290.0,32.0,51.0,66.0,58.0,53.0,60.0,41.0,54.0,48.0,42.0,49.0
13,Damoh,2847.0,2827.0,193.0,19.0,99.0,99.0,99.0,98.0,97.0,78.0,87.0,82.0,86.0,87.0
14,Datia,1469.0,1606.0,114.0,5.0,77.0,85.0,81.0,84.0,80.0,70.0,79.0,74.0,75.0,72.0
15,Dewas,3454.0,3007.0,207.0,21.0,69.0,80.0,74.0,75.0,71.0,54.0,68.0,61.0,64.0,59.0
16,Dhar,5093.0,4156.0,308.0,32.0,70.0,85.0,78.0,81.0,73.0,66.0,82.0,74.0,77.0,70.0
17,Dindori,2022.0,2831.0,137.0,21.0,55.0,96.0,76.0,92.0,92.0,43.0,88.0,66.0,83.0,84.0
18,Guna,3060.0,3011.0,199.0,31.0,78.0,88.0,83.0,78.0,68.0,69.0,83.0,76.0,71.0,60.0
19,Gwalior,3595.0,3194.0,241.0,19.0,86.0,91.0,88.0,85.0,85.0,79.0,87.0,83.0,76.0,79.0
20,Harda,1106.0,936.0,67.0,5.0,70.0,87.0,78.0,81.0,80.0,61.0,80.0,70.0,72.0,72.0
21,Indore,5752.0,5234.0,279.0,18.0,73.0,79.0,76.0,74.0,56.0,72.0,78.0,75.0,71.0,54.0
22,Jabalpur,4118.0,3925.0,331.0,41.0,54.0,64.0,59.0,59.0,62.0,40.0,49.0,44.0,44.0,47.0
23,Jhabua,3128.0,2718.0,175.0,18.0,74.0,89.0,82.0,84.0,88.0,66.0,84.0,75.0,77.0,82.0
24,Katni,2502.0,2385.0,188.0,7.0,83.0,92.0,88.0,91.0,67.0,60.0,75.0,68.0,73.0,47.0
25,Khandwa,3342.0,2838.0,228.0,26.0,73.0,84.0,78.0,84.0,84.0,70.0,82.0,76.0,82.0,82.0
26,Khargone,4965.0,3226.0,255.0,31.0,81.0,81.0,81.0,82.0,81.0,76.0,77.0,76.0,77.0,75.0
27,Maihar,1655.0,1675.0,78.0,17.0,55.0,75.0,65.0,55.0,44.0,41.0,50.0,46.0,41.0,31.0
28,Mandla,2281.0,4289.0,223.0,48.0,91.0,99.0,95.0,98.0,99.0,76.0,96.0,86.0,94.0,95.0
29,Mandsaur,2159.0,1401.0,172.0,9.0,85.0,85.0,85.0,80.0,70.0,82.0,82.0,82.0,77.0,67.0
30,Mauganj,1617.0,1538.0,106.0,16.0,79.0,83.0,81.0,43.0,80.0,58.0,70.0,64.0,40.0,64.0
31,Morena,4020.0,3253.0,270.0,15.0,66.0,72.0,69.0,46.0,63.0,53.0,61.0,57.0,36.0,53.0
32,Narmadapuram,2583.0,2442.0,176.0,15.0,83.0,98.0,90.0,95.0,94.0,79.0,97.0,88.0,93.0,91.0
33,NARSINGHPUR,2515.0,2563.0,199.0,22.0,79.0,91.0,85.0,72.0,90.0,57.0,71.0,64.0,57.0,68.0
34,Neemuch,2081.0,1353.0,120.0,9.0,87.0,83.0,85.0,80.0,72.0,81.0,77.0,79.0,72.0,65.0
35,Niwari,1140.0,756.0,75.0,8.0,73.0,66.0,70.0,60.0,56.0,62.0,53.0,58.0,50.0,49.0
36,Pandhurna,663.0,1096.0,65.0,7.0,66.0,80.0,73.0,87.0,86.0,52.0,67.0,60.0,81.0,77.0
37,Panna,2872.0,1895.0,167.0,22.0,100.0,100.0,100.0,100.0,99.0,93.0,95.0,94.0,94.0,94.0
38,Raisen,3893.0,2542.0,240.0,25.0,69.0,79.0,74.0,79.0,79.0,59.0,73.0,66.0,70.0,70.0
39,Rajgarh,5025.0,2465.0,281.0,27.0,82.0,87.0,84.0,83.0,85.0,70.0,79.0,74.0,73.0,76.0
40,Ratlam,3295.0,2103.0,179.0,15.0,67.0,73.0,70.0,74.0,74.0,61.0,67.0,64.0,68.0,67.0
41,Rewa,3542.0,3127.0,185.0,34.0,49.0,56.0,52.0,40.0,51.0,30.0,37.0,34.0,29.0,30.0
42,Sagar,5778.0,4985.0,400.0,40.0,62.0,74.0,68.0,46.0,60.0,50.0,60.0,55.0,39.0,48.0
43,Satna,3284.0,3494.0,157.0,26.0,73.0,79.0,76.0,39.0,61.0,58.0,63.0,60.0,34.0,52.0
44,Sehore,3535.0,3032.0,220.0,17.0,78.0,94.0,86.0,92.0,92.0,70.0,86.0,78.0,82.0,84.0
45,Seoni,1664.0,4722.0,232.0,33.0,67.0,77.0,72.0,75.0,64.0,52.0,60.0,56.0,59.0,54.0
46,Shahdol,1980.0,3772.0,204.0,38.0,79.0,91.0,85.0,85.0,80.0,65.0,83.0,74.0,80.0,72.0
47,Shajapur,2307.0,2049.0,135.0,10.0,61.0,76.0,68.0,74.0,77.0,57.0,71.0,64.0,70.0,74.0
48,Sheopur,1525.0,967.0,79.0,18.0,71.0,66.0,68.0,58.0,58.0,47.0,42.0,44.0,35.0,38.0
49,Shivpuri,3509.0,3438.0,246.0,48.0,60.0,64.0,62.0,43.0,56.0,40.0,45.0,42.0,28.0,40.0
50,Sidhi,3170.0,2862.0,174.0,29.0,74.0,77.0,76.0,69.0,65.0,56.0,62.0,59.0,48.0,48.0
51,Singrauli,3230.0,3000.0,140.0,20.0,66.0,77.0,72.0,45.0,54.0,47.0,60.0,54.0,39.0,43.0
52,Tikamgarh,2835.0,1855.0,175.0,22.0,81.0,74.0,78.0,72.0,69.0,67.0,59.0,63.0,56.0,55.0
53,Ujjain,3940.0,3086.0,213.0,19.0,54.0,72.0,63.0,46.0,60.0,45.0,66.0,56.0,42.0,53.0
54,Umaria,1170.0,2031.0,83.0,15.0,83.0,94.0,88.0,89.0,89.0,67.0,86.0,76.0,80.0,80.0
55,Vidisha,4244.0,3097.0,245.0,19.0,67.0,87.0,77.0,93.0,91.0,62.0,86.0,74.0,92.0,89.0

In [42]:
df1.to_excel("Lifting_06th_October_2024.xlsx")