In [1]:
#https://pbpython.com/pandas-excel-tabs.html

In [1]:
import numpy as np
import pandas as pd

# Combine Multiple Excel Worksheets Into a Single Pandas Dataframe

# Introduction
One of the most commonly used pandas functions is read_excel . This short article shows how you can read in all the tabs in an Excel workbook and combine them into a single pandas dataframe using one command.


The process I will describe works when:

The data is not duplicated across tabs (sheet1 is one full month and the subsequent sheets have only a single month’s worth of data)
The columns are all named the same
You wish to read in all tabs and combine them

In [25]:
# Most of the time, you will read in a specific sheet from an Excel file:
all_sheets = pd.read_excel('2018_Sales_Total_Tabs.xlsx',sheet_name=None)

In [26]:
all_sheets.keys()

dict_keys(['Sheet1', 'Sheet2', 'Sheet3', 'Sheet4', 'Sheet5', 'Sheet6'])

If you carefully look at the documentation, you may notice that if you use sheet_name=None , you can read in all the sheets in the workbook at one time. 

Pandas will read in all the sheets and return a collections.OrderedDict object. For the purposes of the readability of this article, I’m defining the full url and passing it to read_excel . In practice, you may decide to make this one command.

Let’s inspect the resulting all_sheets :

In [11]:
all_sheets.keys()

dict_keys(['Sheet1', 'Sheet2', 'Sheet3', 'Sheet4', 'Sheet5', 'Sheet6'])

If you want to access a single sheet as a dataframe:

In [6]:
all_sheets['Sheet2'].head(2)

,account number,name,sku,quantity,unit price,ext price,date
0,740150,Barton LLC,B1-20000,39,86.69,3380.91,2018-01-01 07:21:51
1,714466,Trantow-Barrows,S2-77896,-1,63.16,-63.16,2018-01-01 10:00:47

In [7]:
all_sheets['Sheet1'].head(3)

,account number,name,sku,quantity,unit price,ext price,date
0,412290,Jerde-Hilpert,S2-77896,43,76.66,3296.38,2018-03-04 23:10:28
1,383080,Will LLC,S1-93683,28,90.86,2544.08,2018-03-05 05:11:49
2,729833,Koepp Ltd,S1-30248,13,44.84,582.92,2018-03-05 17:33:52

In [8]:
all_sheets['Sheet4'].head(5)

,account number,name,sku,quantity,unit price,ext price,date
0,786968,"Frami, Hills and Schmidt",B1-33087,22,79.82,1756.04,2018-01-19 21:53:06
1,412290,Jerde-Hilpert,S1-82801,16,18.96,303.36,2018-01-19 22:40:09
2,688981,Keeling LLC,B1-53102,13,64.38,836.94,2018-01-20 00:00:21
3,740150,Barton LLC,B1-50809,8,19.60,156.80,2018-01-20 01:48:47
4,672390,Kuhn-Gusikowski,S1-27722,3,36.97,110.91,2018-01-20 02:29:57

If we want to join all the individual dataframes into one single dataframe, use pd.concat:

In [9]:
df = pd.concat(all_sheets,ignore_index=True)

In [10]:
df.shape

(299, 7)

In [11]:
df.head()

,account number,name,sku,quantity,unit price,ext price,date
0,412290,Jerde-Hilpert,S2-77896,43,76.66,3296.38,2018-03-04 23:10:28
1,383080,Will LLC,S1-93683,28,90.86,2544.08,2018-03-05 05:11:49
2,729833,Koepp Ltd,S1-30248,13,44.84,582.92,2018-03-05 17:33:52
3,424914,White-Trantow,S2-82423,38,50.93,1935.34,2018-03-05 21:40:10
4,672390,Kuhn-Gusikowski,S1-50961,34,48.20,1638.80,2018-03-06 11:59:00

In [ ]:
df.to_excel("mergeworksheets17thNov.xlsx")