# Merge multiple excel files into a single file

In [1]:
import numpy as np
import pandas as pd

Normally, we’re working with Excel files, and we surely have come across a scenario where we need to merge multiple Excel files into one. The traditional method has always been using a VBA code inside excel which does the job but is a multi-step process and is not so easy to understand. Another method is manually copying long Excel files into one which is not only time-consume, troublesome but also error-prone. 

This task can be done easily and quickly with few lines of code in Python with the Pandas module. First, we need to install the module with pip. So let’s get the installation out of our way.

## Method 1: Using dataframe.append()

Pandas dataframe.append() function is used to append rows of other dataframe to the end of the given dataframe, returning a new dataframe object. Columns not in the original dataframes are added as new columns and the new cells are populated with NaN value.

Syntax : DataFrame.append(other, ignore_index=False, verify_integrity=False, sort=None)

Parameters :

other : DataFrame or Series/dict-like object, or list of these
ignore_index : If True, do not use the index labels. default False.
verify_integrity : If True, raise ValueError on creating index with duplicates. default False.
sort : Sort columns if the columns of self and other are not aligned. default False.
Returns: appended DataFrame

In [3]:
# importing the required modules
import glob

The glob module, which is short for global, is a function that’s used to search for files that match a specific file pattern or name. It can be used to search CSV files and for text in files. 
These patterns are similar to regular expressions but much simpler.

Asterisk (*): Matches zero or more characters.
Question mark (?): Matches exactly one character.
While glob can be used to search for a file with a specific file name, I find it especially handy for reading through several files with similar names. After identifying these files, they can then be concatenated into one dataframe for further analysis.

In [6]:
# Specifying the path to xlsx 
path = "C:\\Users\lenovo\CH - 1\CH5 - Concatenation, Merge\Excel_File1"

In [16]:
# excel files in the path

file_list = glob.glob(path+'/*.xlsx')

In [18]:
file_list

['C:\\Users\\lenovo\\CH - 1\\CH5 - Concatenation, Merge\\Excel_File1\\FoodSales1-1.xlsx',
 'C:\\Users\\lenovo\\CH - 1\\CH5 - Concatenation, Merge\\Excel_File1\\FoodSales2-1.xlsx']

In [6]:
# list of excel files we want to merge.
# pd.read_excel(file_path) reads the excel
# data into pandas dataframe.

excl_list = []

for file in file_list:
    excl_list.append(pd.read_excel(file))

In [7]:
# create a new dataframe to store the 
# merged excel file.
excl_merged = pd.DataFrame()

for excl_file in excl_list:
    excl_merged = excl_merged.append(excl_file,ignore_index=True)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_6552\2223871906.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  excl_merged = excl_merged.append(excl_file,ignore_index=True)

In [8]:
excl_merged

,OrderDate,Region,City,Category,Product,Quantity,UnitPrice,TotalPrice
0,2020-01-01,East,Boston,Bars,Carrot,33,1.77,58.41
1,2020-01-04,East,Boston,Crackers,Whole Wheat,87,3.49,303.63
2,2020-01-07,West,Los Angeles,Cookies,Chocolate Chip,58,1.87,108.46
3,2020-01-10,East,New York,Cookies,Chocolate Chip,82,1.87,153.34
4,2020-01-13,East,Boston,Cookies,Arrowroot,38,2.18,82.84
...,...,...,...,...,...,...,...,...
64,2020-07-12,East,Boston,Crackers,Whole Wheat,42,3.49,146.58
65,2020-07-15,West,Los Angeles,Cookies,Chocolate Chip,75,1.87,140.25
66,2020-07-18,East,New York,Bars,Bran,72,1.87,134.64
67,2020-07-21,East,New York,Cookies,Oatmeal Raisin,56,2.84,159.04
68,2020-07-24,West,San Diego,Bars,Bran,51,1.87,95.37

In [9]:
# exports the dataframe into excel file with
# specified name.
excl_merged.to_excel('total_food_sales.xlsx', index=False)

## Method 2: Using pandas.concat()

The pandas.concat() function does all the heavy lifting of performing concatenation operations along with an axis of Pandas objects while performing optional set logic (union or intersection) of the indexes (if any) on the other axes.

Syntax: concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)

Parameters:

objs: Series or DataFrame objects
axis: axis to concatenate along; default = 0 //along rows
join: way to handle indexes on other axis; default = ‘outer’
ignore_index: if True, do not use the index values along the concatenation axis; default = False
keys: sequence to add an identifier to the result indexes; default = None
levels: specific levels (unique values) to use for constructing a MultiIndex; default = None
names: names for the levels in the resulting hierarchical index; default = None
verify_integrity: check whether the new concatenated axis contains duplicates; default = False
sort: sort non-concatenation axis if it is not already aligned when join is ‘outer’; default = False
copy: if False, do not copy data unnecessarily; default = True
Returns: a pandas dataframe with concatenated data.

#### Example:

In the last example, we worked on only two Excel files with a few rows. Let’s try merging more files each containing approximately 5000 rows and 7 columns. We have 5 files BankE, BankD, BankC, BankB, BankA having historical stock data for respective bank. Let’s merge them into a single ‘Bank_Stocks.xlsx’ file. Here we are using the pandas.concat() method.

In [10]:
path1 = "C:\\Users\lenovo\CH - 1\CH5 - Concatenation, Merge\Book"

In [11]:
F_List = glob.glob(path1+'/*.xlsx')

In [12]:
F_List

['C:\\Users\\lenovo\\CH - 1\\CH5 - Concatenation, Merge\\Book\\BankA.xlsx',
 'C:\\Users\\lenovo\\CH - 1\\CH5 - Concatenation, Merge\\Book\\BankB.xlsx',
 'C:\\Users\\lenovo\\CH - 1\\CH5 - Concatenation, Merge\\Book\\BankC.xlsx',
 'C:\\Users\\lenovo\\CH - 1\\CH5 - Concatenation, Merge\\Book\\BankD.xlsx',
 'C:\\Users\\lenovo\\CH - 1\\CH5 - Concatenation, Merge\\Book\\BankE.xlsx']

In [13]:
List1 = []
for file in F_List:
    List1.append(pd.read_excel(file))

In [14]:
# concatenate all DataFrames in the list
# into a single DataFrame, returns new 
# DataFrame.
Merged_File = pd.concat(List1, ignore_index=True)

In [15]:
Merged_File

            Date    Open    High     Low   Close    Volume Symbol
0     2000-01-03  166.00  170.00  166.00  170.00     33259  BankA
1     2000-01-04  182.00  183.45  171.00  173.80    168710  BankA
2     2000-01-05  170.00  173.90  165.00  166.95    159820  BankA
3     2000-01-06  168.00  170.00  165.30  168.30     85026  BankA
4     2000-01-07  162.15  171.00  162.15  168.35     85144  BankA
...          ...     ...     ...     ...     ...       ...    ...
20533 2020-11-23  375.85  379.35  370.30  375.15   4065424  BankE
20534 2020-11-24  378.00  402.00  376.00  392.25  19485370  BankE
20535 2020-11-25  396.30  404.70  384.40  398.95  18238080  BankE
20536 2020-11-26  400.80  413.00  395.65  410.15  12856261  BankE
20537 2020-11-27  411.00  416.00  408.20  411.55  10593353  BankE

[20538 rows x 7 columns]

In [ ]:
# exports the dataframe into excel file
# with specified name.
Merged_File.to_excel('Bank_Stocks.xlsx', index=False)

### Differences between Concat and Append

Append function will add rows of second data frame to first dataframe iteratively one by one. Concat function will do a single operation to finish the job, which makes it faster than append().

As append will add rows one by one, if the dataframe is significantly very small, then append operation is fine as only a few appends will be done for the number of rows in second dataframe
.
Append function will create a new resultant dataframe instead of modifying the existing one. Due to this buffering and creating process, Append operation’s performance is less than concat() function. However Append() is fine if the number of append operation is a very few. If there are a multiple append operations needed, it is better to use concat().